### ISSUE TITLE
Support `XDG_STATE_HOME`

### ISSUE THREAD

**Issue by hyperupcall** [folder/xdg#1]
The environment variable `XDG_STATE_HOME` is a relatively recent addition to the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), but I don't see it used in this repository - adding support for it would be very nice

**Comment by jonschlinkert** [comment]
Would you like to do a PR for discussion?

**Comment by hyperupcall** [comment]
I made the pr - thoughts?

**Comment by jonschlinkert** [comment]
awesome thanks! reviewing tonight!
